version: "3"
services:
  frontend:
    build:
      context: ./frontend/heritage
      target: production
      args:
        - VITE_API_URL=${API_URL}
    ports:
      - "${CLIENT_APP_PORT}:3000"

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    command:
      - sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8001
    ports:
      - "${SERVER_APP_PORT}:${SERVER_APP_PORT}"
    volumes:
      - ./backend:/app
