# Generated by Django 5.1 on 2024-08-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
