# Generated by Django 5.1 on 2024-08-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0002_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(max_length=20),
        ),
    ]
